name: weather
description: A cross-platform weather application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  json_annotation: ^3.1.1
  geolocator: ^6.1.13
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  mockito: ^4.1.3

flutter:
  uses-material-design: true
