name: weather
description: A cross-platform weather application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  json_annotation: ^4.0.0
  geolocator: ^7.0.1
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  mockito: ^5.0.0

flutter:
  uses-material-design: true
